# Default values for proxysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: proxysql/proxysql
  tag: 2.4.7
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 6033
  
externalService:
  enabled: false
  # annotations:
  #   foo: bar
  serviceType: NodePort
  port: 6033

ingress:
  enabled: false
#   annotations: {}
#     # kubernetes.io/ingress.class: proxysql
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: 10.18.120.41
#       paths: []

#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector:
  node_type: app

tolerations: []

affinity: {}

pmm:
  enabled: true
  image:
    repository: percona/pmm-client
    tag: "2.32.0"
  resources:
    requests:
      memory: 150M
      cpu: 300m
  env:
    agentConfigPath: /tmp/pmm-agent.yaml
    #set args when helm apply or you can set example 10.1.2.101:4443
    agentServerAddress: {}
    agentServerUsername: admin
    agentServerPassword: admin
    agentProxySqlUsername: admin
    agentProxySqlpassword: admin
